"""add_customer_password

Revision ID: b4c2a9e1418d
Revises: 21952522e20f
Create Date: 2026-01-16 16:21:09.211551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c2a9e1418d'
down_revision: Union[str, Sequence[str], None] = '21952522e20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default='change_me'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('customers', 'hashed_password')
    # ### end Alembic commands ###
